---
- name: Apply compliance profile
  hosts: "{{ create_vm_vm_name | default(omit) }}"
  become: true
  vars:
    compliance_profile: undef

  tasks:
    - name: Check os type
      ansible.builtin.assert:
        that: "ansible_os_family == 'RedHat'"
      tags: always

    - name: Run Security Compliance Profile!!
      ansible.builtin.include_role:
        name: "redhatofficial.rhel{{ ansible_distribution_major_version }}_{{ compliance_profile }}"
      vars:
        sudo_require_authentication: false
        sudo_remove_nopasswd: false
        reboot_required: false
        medium_severity: false
      tags: always
...
