---
- name: Post_Deploy Validation
  gather_facts: false
  tasks:
    - name: Wait for SSH connection to become available
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 180
        sleep: 15
      register: connection_wait
      ignore_errors: yes

    - name: Print Linux kernel version
      ansible.builtin.shell: uname -r
      when: "'Linux' in vmi_guest_os_info['name']"
      register: uname_output
      changed_when: false

    - name: Show kernel version
      ansible.builtin.debug:
        msg: "{{ uname_output.stdout }}"
      when: uname_output is defined

    - name: Perform ping on Windows
      ansible.windows.win_ping:
      when: vmi_guest_os_info == {}
