---
- name: Pre_Deploy - Validate Infrastructure
  hosts: all
  gather_facts: false
  tasks:

  - name: Print ansible_play_hosts_all
    debug:
      msg: "{{ ansible_play_hosts_all }}"

  - name: Block for VMware
    block:
    - name: Check VMware Infrastructure
      debug:
        msg: "Validate VMware Infrastructure"

    - name: Validation is in progress
      ansible.builtin.pause:
        seconds: 1
    when: deployment_platform is defined and 'vmware' is in deployment_platform

  - name: Block for AWS
    block:
    - name: Check AWS Infrastructure
      debug:
        msg: "Validate AWS Infrastructure"

    - name: Validation is in progress
      ansible.builtin.pause:
        seconds: 1
    when: deployment_platform is defined and 'aws' is in deployment_platform

  - name: Block for OCP Virtualization
    block:
    - name: Check OCP-V Infrastructure
      debug:
        msg: "Validate OCP-V Infrastructure"

    - name: Validation is in progress
      ansible.builtin.pause:
        seconds: 1
    when: deployment_platform is defined and 'ocpvirt' is in deployment_platform
