---
- name: Create an incident in ServiceNow using facts from a host
  hosts: "{{ create_vm_vm_name | default('all')}}"
  gather_facts: false
  connection: local

  pre_tasks:
  - name: Set variables
    ansible.builtin.set_fact:
      servicenow_ticket: create
      incident_description: "Provisioning has been failed"
      sn_description: |-
        Provisioning has been failed with the following server!!
        hostname: {{ inventory_hostname }}
      
    run_once: yes

  roles:
    - demo.process.snow_ticket
  run_once: yes
