---
- name: Create a change request
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    servicenow_cr: create_wait
    cr_short_description: "Provision Change Request"
    cr_description: "{{ change_owner | default('Ansible') }} requests a server in {{ change_environment | default('Dev') }} to provision }}"

  roles:
    - demo.process.snow_change_request


