---
- name: Create a standard SNOW change request
  hosts: all
  gather_facts: false
  connection: local

  vars:
    servicenow_cr: create
    cr_short_description: "Provision Change Request"
    cr_description: "{{ change_owner | default('Ansible') }} requests to provision in {{ change_environment | default('Dev') }}"

  roles:
    - demo.process.snow_change_request
  run_once: true

  post_tasks:

    - name: Update to scheduled the change request in ServiceNow
      servicenow.itsm.change_request:
        state: scheduled
        number: "{{ request.record.number }}"
        assignment_group: CAB Approval
      run_once: true

    - name: Update to implement the change request in ServiceNow
      servicenow.itsm.change_request:
        state: implement
        number: "{{ request.record.number }}"
        assignment_group: CAB Approval
      run_once: true

    - name: Store Change Record Detail
      ansible.builtin.set_fact:
         request: "{{ request }}"
         cacheable: yes
      run_once: true


# ==== Matter Most Message  ====#
- name: Fail if required variables are not set
  ansible.builtin.fail:
    msg: "Both Mattermost Instance and token must be set!"
  when: mattermost_instance | default('') | trim == '' or mattermost_token | default('') | trim == ''

- name: Send notification message via Mattermost
  community.general.mattermost:
    url: "{{ mattermost_instance }}"
    api_key: "{{ mattermost_token }}"
    attachments:
      - text: "!!!! Provisioning Request !!!!"
        color: "#ff00dd"
        title: "Provisioning Standard Change Record has been created"
        fields:
          - title: The following Change Record has been created
            value: "<{{ lookup('ansible.builtin.env', 'SN_HOST') }}/nav_to.do?uri=change_request.do?sysparm_query=number={{request.record.number }}>"
            short: true
  delegate_to: localhost