---
- name: Update CMDB table
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Create CMDB CI
    ansible.builtin.import_role:
      name: demo.process.snow_cmdb
    vars:
      create_vm_vm_name: "{{ create_vm_vm_name }}"
      owner: "{{ create_vm_aws_owner_tag }}"
      ip_addr: "{{ public_ip }}"
      classification: "Development"
      os: "{{ ansible_distribution }}"
    delegate_to: localhost
