---
- name: Update CMDB table
  hosts: all
  # gather_facts: false
  # connection: local

  vars:
    create_vm_vm_name: "{{ inventory_hostname }}"
    owner: "{{ create_vm_aws_owner_tag }}"
    ip_addr: "{{ public_ip }}"
    classification: "Development"
    os: "{{ ansible_distribution }}"

  roles:
    - demo.process.snow_cmdb
  delegate_to: localhost
