---
- name: Update CMDB table
  hosts: "{{ create_vm_vm_name | default('all') }}"
  gather_facts: false
  connection: local

  vars:
    owner: "{{ create_vm_aws_owner_tag }}"
    ip_addr: "{{ public_ip }}"
    classification: "Development"
    os: "Linux Red Hat"

  roles:
    - demo.process.snow_cmdb
