---
- name: Apply {{ compliance_profile }} Benchmark security/compliance hardenning to the NEW RHEL 9 VM 
  hosts: "{{ create_vm_vm_name | default(omit) }}"
  become: true
  become_method: sudo
  collections:
    - demo.compliance

  tasks: 

    - name: Run Openscap Scan
      ansible.builtin.include_role:
        name: openscap-scanner
      vars:
        openscap_profile: xccdf_org.ssgproject.content_profile_{{ compliance_profile | lower }}

    - name: Fetch report to controller
      ansible.builtin.fetch:
        src: "/tmp/oscap-report-{{ ansible_nodename }}-{{ v_stage }}.html"
        dest: "./oscap-report-{{ ansible_nodename }}-{{ v_stage }}.html"
        flat: true

    - name: copy report to Report Server 
      ansible.builtin.copy:
        src: "./oscap-report-{{ ansible_nodename }}-{{ v_stage }}.html"
        dest: "/var/www/html/oscap-report-{{ ansible_nodename }}-{{ v_stage }}.html"
        mode: "0664"
      delegate_to: "{{ report_server }}"

    - ansible.builtin.file:
        path: "./oscap-report-{{ ansible_nodename }}-{{ v_stage }}.html"
        state: absent
