---
- name: Create CR
  ansible.builtin.include_tasks: servicenow_create.yml
  when:
    - servicenow_cr == "create"

- name: Create CR_Wait
  ansible.builtin.include_tasks: servicenow_create_wait.yml
  when:
    - servicenow_cr == "create_wait"

- name: Create CR_Slack_Wait
  ansible.builtin.include_tasks: servicenow_create_slack_wait.yml
  when:
    - servicenow_cr == "CR_Slack_Wait"

- name: Implement CR
  ansible.builtin.include_tasks: servicenow_implement.yml
  when:
    - servicenow_cr == "implement"
    - request is defined

- name: Close CR
  ansible.builtin.include_tasks: servicenow_close.yml
  when:
    - servicenow_cr == "close"
    - request is defined

- name: Close CR
  ansible.builtin.include_tasks: servicenow_close_cr.yml
  when:
    - servicenow_cr == "close"
    - change_request_number is defined

- name: Cancel CR
  ansible.builtin.include_tasks: servicenow_canceled.yml
  when:
    - servicenow_cr == "canceled"
    - request is defined

- name: Cancel CR
  ansible.builtin.include_tasks: servicenow_canceled_cr.yml
  when:
    - servicenow_cr == "canceled"
    - change_request_number is defined

- name: Delete CR
  ansible.builtin.include_tasks: servicenow_deleted.yml
  when:
    - servicenow_cr == "absent"
    - request is defined
