---
- name: Create ServiceNow Change Request
  servicenow.itsm.change_request:
    type: normal
    short_description: "{{ cr_short_description }}"
    description: "{{ cr_description }}"
    priority: high
    risk: moderate
    impact: low
    assignment_group: CAB Approval
    state: assess
  register: request
  until: request.changed is defined
  retries: 5
  delay: 5
  delegate_to: localhost

- name: Pass along request information
  ansible.builtin.set_stats:
    data:
      request: "{{ request }}"
    per_host: false
  delegate_to: localhost

- name: Send Slack Notification
  ansible.builtin.include_role:
    name: demo.process.slack
  vars:
    slack_message: |-
      {% for host in groups['all'] %}@{{hostvars[host].app_owner}} {% endfor %}
      A change request has been raised for your servers.
      Please click on this URL to review: <{{ lookup('ansible.builtin.env', 'SN_HOST') }}/nav_to.do?uri=change_request.do?sysparm_query=number={{request.record.number }}>


# - name: Send Approval e-mail
#   community.general.mail:
#     host: "{{ EMAIL_HOST }}"
#     username: "{{ EMAIL_USERNAME }}"
#     password: "{{ EMAIL_PASSWORD }}"
#     port: "{{ EMAIL_PORT }}"
#     subject: Approval request for ServiceNow Change Request {{ request.record.number }}
#     body: "You have a new CR Approval request. Please click on this URL to approve: {{ lookup('env', 'SN_HOST') }}nav_to.do?uri=change_request.do?sysparm_query=number={{
#       request.record.number }}"
#     from: tower@shadowman.dev
#     to: "{{ to_email }}"
#   delegate_to: localhost

- name: Wait for Change Request approval
  servicenow.itsm.change_request_info:
    number: "{{ request.record.number }}"
  until: change_request_status.records[0].state == "scheduled"
  retries: 50
  delay: 10
  register: change_request_status
  delegate_to: localhost

- name: Update to implement the change request in ServiceNow
  servicenow.itsm.change_request:
    state: implement
    number: "{{ request.record.number }}"
    assignment_group: CAB Approval
  delegate_to: localhost
