---
- name: Make sure slack token is provided
  ansible.builtin.assert:
    that: 
      - slack_token is defined
      - aap_base_url is defined
      - slack_channel_name is defined
      - slack_message_type is defined

- name: Send notification message via Slack
  community.general.slack:
    token: "{{ slack_token }}"
    msg: "{{ slack_message }}"
    channel: '#{{ slack_channel_name }}'
    username: "{{ slack_username }}"
    parse: 'none'
  # when: slack_message_type == 'pull_request'


