---
- name: Close an incident in ServiceNow
  servicenow.itsm.incident:
    state: closed
    number: "{{ ticket_number }}"
    close_code: Solved (Permanently)
    close_notes: "{{ comment }}"
  delegate_to: localhost
