---
- name: linux-hyperv
  hosts: "{{ hyperv_host_name | default(omit) }}"
  
  tasks:
  - name: Create switch LAB-Test that is bridged to Adapter "Ethernet"
    gocallag.hyperv.switch:
      name: LAB-External
      netAdapterName: "Ethernet"
      switchType: External
      allowManagementOS: false
      state: present

  - name: Create almalinux9 VM
    gocallag.hyperv.vm:
        name: almalinux9
        state: present

  - name: Get ID of our VM
    gocallag.hyperv.vm_info:
        names: 
        - almalinux9
        power_state: 'Off'
    register: info

  - gocallag.hyperv.disk:   
        path: 'c:\temp\almalinux9-disk0.vhd'
        size: 100
        state: present

  - name: Add disk to almalinux9
    gocallag.hyperv.vm_disk:   
        id: '{{ info.output.value[0].Id }}'
        path: 'c:\temp\almalinux9-disk0.vhd'
        state: present

  - name: add almalinux9 iso to test vm 
    gocallag.hyperv.vm_dvddrive:   
        id: '{{ info.output.value[0].Id }}'
        path: c:\temp\almaLinux-9.3-x86_64-dvd.iso
        state: present
    register: check
  - gocallag.hyperv.vm_setbootorder:   # This syntax order only works for generation 1, and yes, all 4 items must be present in the order you want, ie you can't leave out any items.
        id: '{{ info.output.value[0].Id }}'
        order:
          - "CD"
          - "IDE"
          - "LegacyNetworkAdapter"
          - 'Floppy'
  - name: Power 'on'
    gocallag.hyperv.vm_power:
        id: '{{ info.output.value[0].Id }}'
        state: 'on'
    register: info