---
- name: Install Hyper-V
  hosts: "{{ hyperv_host_name | default(omit) }}"
  gather_facts: no
  tasks:
    - name: Install Hyper-V with GUI and PowerShell tools
      win_feature:
        name:
          - Hyper-V
          - RSAT-Hyper-V-Tools
          - Hyper-V-PowerShell
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: install_result

    - name: Reboot if necessary
      win_reboot:
      when: install_result.reboot_required

    - name: Wait 600 seconds for target connection to become reachable/usable
      ansible.builtin.wait_for_connection:
        connect_timeout: "{{ wait_for_timeout_sec | default(5) }}"
        delay: "{{ wait_for_delay_sec | default(0) }}"
        sleep: "{{ wait_for_sleep_sec | default(1) }}"
        timeout: "{{ wait_for_timeout_sec | default(300) }}"