---
controller_projects:
  - name: "Ansible Product Demos"
    description: !unsafe ''
    organization: "Default"
    scm_type: "git"
    scm_url: "https://github.com/ansible/product-demos"
    scm_branch: ""
    scm_clean: false
    scm_delete_on_update: false
    scm_update_on_launch: false
    scm_update_cache_timeout: "0"
    scm_refspec: ""
    allow_override: false
    update_project: false
    timeout: "0"
  - name: "Ansible Cloud Content Lab - AWS"
    description: !unsafe ''
    organization: "Default"
    scm_type: "git"
    scm_url: "https://github.com/ansible-content-lab/aws.infrastructure_config_demos.git"
    scm_branch: ""
    scm_clean: false
    scm_delete_on_update: false
    scm_update_on_launch: false
    scm_update_cache_timeout: "0"
    scm_refspec: ""
    allow_override: false
    update_project: false
    timeout: "0"
  - name: "Ansible Cloud AWS Demos"
    description: !unsafe ''
    organization: "Default"
    scm_type: "git"
    scm_url: "https://github.com/ansible-cloud/aws_demos.git"
    scm_branch: ""
    scm_clean: false
    scm_delete_on_update: false
    scm_update_on_launch: false
    scm_update_cache_timeout: "0"
    scm_refspec: ""
    allow_override: false
    update_project: false
    timeout: "0"
  - name: "DevOps"
    description: !unsafe ''
    organization: "ACC"
    scm_type: "git"
    scm_url: "https://github.com/sonstar2/ansible_devops_demo.git"
    scm_branch: ""
    scm_clean: true
    scm_delete_on_update: true
    scm_update_on_launch: false
    scm_update_cache_timeout: "0"
    scm_refspec: ""
    allow_override: false
    update_project: false
    timeout: "0"
  - name: "AAP Provisioning"
    description: !unsafe ''
    organization: "ACC"
    scm_type: "git"
    scm_url: "https://github.com/sonstar2/aap_provisioning.git"
    scm_branch: ""
    scm_clean: false
    scm_delete_on_update: false
    scm_update_on_launch: false
    scm_update_cache_timeout: "0"
    scm_refspec: ""
    allow_override: false
    update_project: false
    timeout: "0"

