---
controller_credential_types:
  - name: "Insights Collection"
    description: !unsafe ''
    kind: "cloud"
    inputs:
      fields:
      - id: insights_user
        type: string
        label: Insights User
      - id: insights_password
        type: string
        label: Insights Password
        secret: true

    injectors:
      env:
        INSIGHTS_USER: !unsafe '{{ insights_user }}'
        INSIGHTS_PASSWORD: !unsafe '{{ insights_password }}'
  - name: "ServiceNow"
    description: !unsafe ''
    kind: "cloud"
    inputs:
      fields:
      - id: instance
        type: string
        label: Instance
      - id: username
        type: string
        label: Username
      - id: password
        type: string
        label: Password
        secret: true
      required:
      - instance
      - username
      - password

    injectors:
      env:
        SN_HOST: !unsafe '{{instance}}'
        SN_PASSWORD: !unsafe '{{password}}'
        SN_USERNAME: !unsafe '{{username}}'
...
