---
eda_decision_environments:
  - name: "Default Decision Environment"
    description: ""
    image_url: "registry.redhat.io/ansible-automation-platform-25/de-supported-rhel8:latest"
    organization: "Default"
    eda_credential: "Decision Environment Container Registry"
  - name: "Hub Default Decision Environment"
    description: ""
    image_url: "ip-172-31-7-190.ap-southeast-2.compute.internal/de-supported-rhel8:latest"
    organization: "Default"
    eda_credential: "Hub Decision Environment Container Registry"
  - name: "DE SNOW"
    description: ""
    image_url: "quay.io/fredmkson/ee_snow:latest"
    organization: "ACC"
    eda_credential: "Hub Decision Environment Container Registry"

