---
# defaults file for ocpvirt-manage

#    v_ocp_cluster_api: https://api.cluster-4tj5d.dynamic.redhatworkshops.io:6443
#    v_change_request_number: CHG0030005
#    v_vm_name: minatest01
#    v_vm_namespace: mina
#    v_vm_label: cbademo
#    v_vm_instancetype: u1.large
#    v_vm_preference: rhel.9
#    v_vm_datastore: rhel9
#    v_vm_os_disk_size: '30'
#    v_vm_location: Australia
#    v_lcy_environment: Production